### ISSUE TITLE
Contact Us copy

### ISSUE THREAD

**Issue by davidneudorfer** [papertrails/papertrails.co-static#11]
- [ ]  Section Title
- [ ]  Section Description
- [ ] Text Box prefill text
- [ ] Send Message text

![image](https://cloud.githubusercontent.com/assets/547876/14905995/ac1311ba-0d84-11e6-883c-33fa8ef70967.png)

**Comment by anishavasandani** [comment]
Get At Us

We get it, you're OCD. You want to make sure you and your significant other will have the best trip abroad. Cut us some slack, give us 24 hours to get back to you.

Name
Email Address
Digits
Message

**Comment by davidneudorfer** [comment]
> You, you, and your
lets rephrase this.

**Comment by davidneudorfer** [comment]
Working branch: contact-us-copy
