### ISSUE TITLE
Set home page copy

### ISSUE THREAD

**Issue by davidneudorfer** [papertrails/papertrails.co-static#2]
```
                <div class="intro-lead-in">Welcome To Our Studio!</div>
                <div class="intro-heading">It's Nice To Meet You</div>
                <a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>
```
https://github.com/papertrails/papertrails.co/blob/gh-pages/_includes/header.html#L47-L49

**Comment by davidneudorfer** [comment]
Current look:
![image](https://cloud.githubusercontent.com/assets/547876/14905196/7843cfa8-0d7c-11e6-8581-002715ac27c9.png)

**Comment by davidneudorfer** [comment]
`TELL ME MORE` smooth scrolls to the first section in the list set here #1

**Comment by anishavasandani** [comment]
Welcome to Paper Trails!

Let's plan your next trip together.
