### ISSUE TITLE
Set icons for services

### ISSUE THREAD

**Issue by davidneudorfer** [papertrails/papertrails.co-static#5]
https://design.google.com/icons/
https://useiconic.com/open
https://thenounproject.com/

Find 3 icons that match service titles in #3

**Comment by anishavasandani** [comment]
![image](https://cloud.githubusercontent.com/assets/4381590/15624692/fe152608-245c-11e6-87c4-bd43aff6a265.png)
Itineraries -- https://thenounproject.com/search/?q=checklist&i=432895
![image](https://cloud.githubusercontent.com/assets/4381590/15624678/6c256e88-245c-11e6-884f-7bb53911f5f2.png)
Printed Map -- https://thenounproject.com/search/?q=maps&i=96666
![image](https://cloud.githubusercontent.com/assets/4381590/15624699/2d130812-245d-11e6-8ca0-9cb86d1d77e5.png)
Local Connect -- https://thenounproject.com/search/?q=service+bell&i=374227
