### ISSUE TITLE
Update or rename Team

### ISSUE THREAD

**Issue by davidneudorfer** [papertrails/papertrails.co-static#8]
- [x] section name
- [ ] section description

https://github.com/papertrails/papertrails.co/blob/gh-pages/_includes/team.html#L6-L7

- [ ] section footer

https://github.com/papertrails/papertrails.co/blob/gh-pages/_includes/team.html#L33

- [x] title - Anisha
- [x] title - David
- [x] social - Anisha
- [x] social - David

https://github.com/papertrails/papertrails.co/blob/gh-pages/_config.yml#L11-L32

- [ ] profile picture - Anisha
- [ ] profile picture - David
- [ ] profile picture - Skyr

https://github.com/papertrails/papertrails.co/tree/gh-pages/img/team

![image](https://cloud.githubusercontent.com/assets/547876/14905972/51cc5928-0d84-11e6-90f7-121ee1f64f7e.png)

**Comment by anishavasandani** [comment]
Anisha Vasandani
Chief Map Maker & Guide
instagram: anishavasandani

David Neudorfer
Map Maker & Emotional Support Engineer
instagram: davidneudorfer

**Comment by davidneudorfer** [comment]
https://github.com/papertrails/papertrails.co/tree/add-guides
